---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: bridge
  namespace: telemetry
spec:
  bootstrapServers: cluster-kafka-bootstrap:9092
  enableMetrics: true
  http:
    port: 8080
  replicas: 1
